fcm_notification/urls.py
from django.urls import path

from fcm_notification.api_views import (
    RegisterFcmTokenAPI, PushMessageAPI, SendPushMessageAPIView, PushMessageImageAPI
)
from fcm_notification.views import (
    create_push_message, PushMessageList, message_details, BulkMessageRequestList,
    create_bulk_message_request, SendBulkMessage, BulkMessageReceiversList, BulkMessageSendRequestView,
    BulkMessageSchedulesView, BulkMessageTagsView, edit_message, send_message, send_message_success
)

urlpatterns = [
    path('message/create', create_push_message, name='create_push_message'),
    path('message', PushMessageList.as_view(), name='push_message_list'),
    path('message/<int:message_id>', message_details, name='message_details'),
    path('message/bulk', BulkMessageRequestList.as_view(), name='bulk_message_list'),
    path('message/bulk/create', create_bulk_message_request, name='create_bulk_message'),
    path('message/bulk/<int:request_id>/send', SendBulkMessage.as_view(), name='send_bulk_message'),
    path('message/bulk/<int:request_id>/receivers', BulkMessageReceiversList.as_view(), name='bulk_message_receivers'),
    path('message/bulk/<int:request_id>/send-request', BulkMessageSendRequestView.as_view(),
         name='bulk_message_send_request'),
    path('message/bulk/<int:request_id>/schedules', BulkMessageSchedulesView.as_view(), name='bulk_message_schedules'),
    path('message/bulk/<int:request_id>/tags', BulkMessageTagsView.as_view(), name='bulk_message_tags'),
    path('message/<int:message_id>/edit', edit_message, name='edit_message'),
    path('message/<int:message_id>/send', send_message, name='send_message'),
    path('message/<int:message_id>/sent', send_message_success, name='message_sent'),
    path('fcm/register', RegisterFcmTokenAPI.as_view(), name='register_fcm_token'),
    path('message', PushMessageAPI.as_view(), name='add_push_message_api'),
    path('message/<int:id>', PushMessageAPI.as_view(), name='get_push_message_api'),
    path('message/<int:message_id>/send/<mobile:mobile_no>', SendPushMessageAPIView.as_view(),
         name='send_push_message_api'),
    path('message/image', PushMessageImageAPI.as_view(), name='push_message_image_api'),
]

fcm_notification/models.py
import uuid
from argparse import FileType

from django.core.validators import MinLengthValidator, MinValueValidator, URLValidator
from django.db import models
from django.forms.fields import URLField as FormURLField
from django_celery_beat.models import PeriodicTask

from fcm_notification.utilities.common_services import image_upload_path, notification_number_file_upload_path
from fcm_notification.utilities.validators import validate_file_size

MESSAGE_TYPES = (
    ('INFO', 'INFO'), 
    ('FILE_UPLOAD', 'FILE_UPLOAD'), 
    ('IMAGE_UPLOAD', 'IMAGE_UPLOAD'), 
    ('LINK', 'LINK'),
    ('POPUP_MESSAGE', 'POPUP_MESSAGE'),
)


class MessageCategory(models.TextChoices):
    GENERIC = 'GENERIC'
    CUSTOM = 'CUSTOM'


IMAGE_RESOLUTION_TYPES = (
    ('LOW', 'LOW'),
    ('MEDIUM', 'MEDIUM'),
    ('HIGH', 'HIGH'),
)

MSG_CONTENT_TYPE = (
    ('text', 'TEXT'),
    ('html', 'HTML'),
)

BULK_NOTIFICATION_STATUS = (
    (1, 'PROCESSING'),
    (2, 'READY'),
)

BULK_NOTIFICATION_SEND_STATUS = (
    (1, 'SCHEDULED'),
    (2, 'PROCESSING'),
    (3, 'COMPLETE'),
    (4, 'CANCELED'),
    (5, 'IN_PROGRESS'),
)


class ReceiverType(models.TextChoices):
    FILE = 'FILE'
    TG = 'TG'


class BulkScheduleType(models.TextChoices):
    ONE_TIME = 'ONE_TIME'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'


class AppInstallStatus(models.TextChoices):
    ACTIVE = 'ACTIVE'
    UNINSTALLED = 'UNINSTALLED'


class AiURLFormField(FormURLField):
    default_validators = [URLValidator(
        schemes=['http', 'https', 'ftp', 'ftps', 'external-http', 'external-https'])]


class AiURLField(models.CharField):
    default_validators = [URLValidator(
        schemes=['http', 'https', 'ftp', 'ftps', 'external-http', 'external-https'])]
    description = "URL"

    def __init__(self, verbose_name=None, name=None, **kwargs):
        kwargs.setdefault('max_length', 200)
        super().__init__(verbose_name, name, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        if kwargs.get("max_length") == 200:
            del kwargs['max_length']
        return name, path, args, kwargs

    def formfield(self, **kwargs):
        return super().formfield(**{
            'form_class': AiURLFormField,
            **kwargs,
        })


class FcmToken(models.Model):
    device_id = models.CharField(max_length=50, unique=True)
    token = models.CharField(max_length=255)
    app_version_number = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    app_status = models.CharField(
        max_length=15, null=False, blank=False, default=AppInstallStatus.ACTIVE.name,
        choices=AppInstallStatus.choices
    )

    class Meta:
        indexes = [
            models.Index(fields=['app_status'])
        ]

    def __str__(self):
        return self.device_id


class ImageRequest(models.Model):
    file_type = models.ForeignKey(FileType, on_delete=models.CASCADE)
    description = models.CharField(max_length=250, blank=True, null=True)
    resolution = models.CharField(choices=IMAGE_RESOLUTION_TYPES, max_length=8)
    is_live = models.BooleanField(default=False)

    class Meta:
        abstract = True


class ActionMessage(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return str(self.title)

    class Meta:
        abstract = True


class PushMessageImage(models.Model):
    thumbnail_img = models.ImageField(null=True, upload_to=image_upload_path, validators=[validate_file_size])
    full_img = models.ImageField(null=True, upload_to=image_upload_path, validators=[validate_file_size])


class PushMessage(models.Model):
    title = models.CharField(max_length=60)
    summary = models.CharField(max_length=250)
    body = models.CharField(max_length=5000)
    content_type = models.CharField(max_length=4, choices=MSG_CONTENT_TYPE, default='text')
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(choices=MESSAGE_TYPES, max_length=20)
    image = models.ForeignKey(PushMessageImage, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.CharField(choices=MessageCategory.choices, max_length=15)

    def __str__(self):
        return "{} - {}".format(self.id, self.title)


class FileRequestMessage(ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)


class FileTypeRequest(ImageRequest):
    title = models.CharField(max_length=100)
    file_request_message = models.ForeignKey(FileRequestMessage, on_delete=models.CASCADE, related_name='file_type_request_set')


class ImageRequestMessage(ImageRequest, ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    min_files = models.PositiveSmallIntegerField()
    max_files = models.PositiveSmallIntegerField()


class LinkMessage(ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    link_url = AiURLField()


class PopupMessage(models.Model):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    button_text = models.CharField(max_length=50, null=False, blank=False)
    display_type = models.CharField(max_length=25, null=False, blank=False, choices=(
        ('COMPLETE_MESSAGE', 'COMPLETE_MESSAGE'),
        ('IMAGE_MESSAGE', 'IMAGE_MESSAGE'),
    ))
    action_type = models.CharField(max_length=25, null=False, blank=False, choices=(
        ('OPEN_URL', 'OPEN_URL'),
        ('OPEN_ACTIVITY', 'OPEN_ACTIVITY'),
        ('DISMISS', 'DISMISS'),
    ))
    action_data = models.CharField(max_length=200, null=True, blank=True)
    start_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    min_delay = models.IntegerField(null=True, blank=True, default=0)


class MessageDeliveryLog(models.Model):
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=11, db_index=True)
    device_id = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=150)


class EventNotification(models.Model):
    event = models.PositiveSmallIntegerField(choices=EVENTS, unique=True)
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationRequest(models.Model):
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000, null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=BULK_NOTIFICATION_STATUS, default=1)
    receiver_count = models.IntegerField(null=False, default=0)
    created_by = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    receiver_type = models.CharField(max_length=15, null=False, blank=False, choices=ReceiverType.choices)

    class Meta:
        indexes = [
            models.Index(fields=['receiver_type'])
        ]

    def __str__(self):
        return str(self.title)


class BulkNotificationFile(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE)
    uploaded_file = models.FileField(
        null=False,
        max_length=150,
        upload_to=notification_number_file_upload_path
    )
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationReceiver(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE, related_name='receivers')
    mobile = models.CharField(max_length=11, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['mobile'], name='idx_bulk_notif_receiver_mobile')
        ]

    def __str__(self):
        return self.mobile


class BulkNotificationSendRequest(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=BULK_NOTIFICATION_SEND_STATUS, null=False, blank=False)
    receiver_count = models.IntegerField(null=False, blank=False)
    chunk_size = models.IntegerField(null=True, blank=True)
    total_chunk = models.IntegerField(null=True, blank=True)
    created_by = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    schedule_time = models.DateTimeField(null=True, blank=True)
    chunk_delay = models.IntegerField(null=False, blank=False, default=0)
    active_user_count = models.IntegerField(null=False, default=0)
    total_success = models.IntegerField(null=False, default=0)
    total_fail = models.IntegerField(null=False, default=0)
    message = models.ForeignKey(PushMessage, null=True, blank=True, on_delete=models.SET_NULL, related_name='+')


class BulkNotificationSendCount(models.Model):
    send_request = models.ForeignKey(BulkNotificationSendRequest, on_delete=models.CASCADE, related_name='send_counts')
    success_count = models.IntegerField(default=0, null=False, blank=False)
    failed_count = models.IntegerField(default=0, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationSchedule(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE, related_name='schedules')
    task = models.ForeignKey(PeriodicTask, on_delete=models.CASCADE)
    schedule_type = models.CharField(max_length=15, null=False, blank=False, choices=BulkScheduleType.choices)
    schedule_time = models.TimeField(null=False, blank=False)
    should_repeat = models.BooleanField(null=False, blank=False, default=False)

fcm_notification/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from fcm_notification.models import MESSAGE_TYPES, FcmToken, PushMessage, BulkNotificationRequest
from fcm_notification.utilities.validators import MOBILE_REGEX

MESSAGE_TYPE_FILTERS = (('', '-- all --'),) + MESSAGE_TYPES


class SendPushMessageForm(forms.Form):
    mobile = forms.RegexField(regex=MOBILE_REGEX, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'minlength': 11, 'maxlength': 11}))

    def clean_mobile(self):
        mobile_no = self.cleaned_data['mobile']
        if mobile_no:
            device_ids = RegisteredUser.objects.filter(mobile=mobile_no, device_status='active').values_list('device_id')
            if len(device_ids) == 0:
                raise ValidationError("No active device found with this mobile")

            device_id_list = [x[0] for x in device_ids]
            fcm_toke_count = FcmToken.objects.filter(device_id__in=device_id_list).count()
            if fcm_toke_count == 0:
                raise ValidationError("No active device of this mobile is registered to Firebase")
        
        return mobile_no


class SearchMessageForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control mx-2'}))
    type = forms.ChoiceField(required=False, choices=MESSAGE_TYPE_FILTERS, widget=forms.Select(attrs={'class': 'form-control mx-2'}))


class SearchBulkMessageForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control mx-2'}))


class SearchBulkMessageReceiverForm(forms.Form):
    mobile = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control mx-2', 'minlength': '11', 'maxlength': '11'}))


class EditMessageForm(forms.ModelForm):
    class Meta:
        model = PushMessage
        fields = ('title', 'summary', 'body', )


class GetPromoForm(forms.Form):
    app_version = forms.IntegerField(min_value=1, max_value=2147483647, required=True)


class CreateBulkMessageForm(forms.ModelForm):
    receiver_list = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control-file', 'accept': ".csv"}),
        validators=[FileExtensionValidator(allowed_extensions=['csv'], message='Only csv file is allowed')]
    )

    class Meta:
        model = BulkNotificationRequest
        exclude = ('created_by', 'status', 'receiver_count')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
        }


class CreateTgNotificationForm(forms.ModelForm):
    class Meta:
        model = BulkNotificationRequest
        exclude = ('created_by', 'status', 'receiver_count')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
            'receiving_tags': forms.SelectMultiple(attrs={'class': 'form-control', 'required': True}),
        }

fcm_notification/templates/notification/bulk_push/create.html
{% extends "notification/base.html" %}

{% block 'extra_head' %}
<style type="text/css">
.form-control-file {
  border: 1px solid #ced4da;
  padding: 5px;
  border-radius: .25rem;
  color: #495057;
}
</style>
{% endblock %}

{% block 'main_content' %}
  <div class="container">
    <h3 class="my-2 pb-1">Create bulk notification</h3>
    <div class="row my-4">
      <div class="col">
        <form class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label>Title of the campaign</label>
            {{ form.title }}
            {% if form.title.errors %}
              {% for error in form.title.errors %}
                <div class="text-danger small mb-2">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-group">
            <label>Select the message to send</label>
            {{ form.message }}
            {% if form.message.errors %}
              {% for error in form.message.errors %}
                <div class="text-danger small mb-2">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-group">
            <label>Upload file with comma separated mobile number (*.csv)</label>
            {{ form.receiver_list }}
            {% if form.receiver_list.errors %}
              {% for error in form.receiver_list.errors %}
                <div class="text-danger small mb-2">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <input type="hidden" name="receiver_type" value="FILE">
          <button type="submit" class="btn btn-primary px-4">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

fcm_notification/templates/notification/bulk_push/list.html
{% extends "notification/base.html" %}
{% load notification_extras %}
{% block 'main_content' %}
<div class="container">
    <h3 class="my-2 pb-1">Bulk notifications</h3>
    <div class="row">
        <div class="col">
            <form class="form-inline my-3" action="">
                <label>Title</label>
                {{ search_form.title }}
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
        <div class="col text-right my-3">
            <a href="{% url 'create_bulk_message' %}" class="btn btn-primary">Add New</a>
        </div>
    </div>

    {% if page_obj %}
    <table class="table mt-3">
        <thead>
            <tr>
                <th>Sl No</th>
                <th>Bulk Request Id</th>
                <th>Title</th>
                <th>#Receivers</th>
                <th>Status</th>
                <th>Created at</th>
                <th class="text-center">Option</th>
            </tr>
        </thead>
        <tbody>
            {% for msg_obj in  page_obj %}
            <tr>
                <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                <td class="text-center">{{ msg_obj.id }}</td>
                <td>{{ msg_obj.title|default_if_none:'N/A' }}</td>
                <td>{{ msg_obj.receiver_count }}</td>
                <td>{{ msg_obj.status }}</td>
                <td>{{ msg_obj.created_at }}</td>
                <td class="pr-0 text-right">
                  {% if msg_obj.get_status_display == 'READY' %}
                    <a href="{% url 'send_bulk_message' msg_obj.id %}" class="btn btn-sm btn-success">Send</a>
                  {% endif %}
                    <a href="{% url 'bulk_message_send_request' msg_obj.id %}" class="btn btn-sm btn-primary">Details</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    {% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=1 %}">&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}

            {% for p in page_range %}
            <li class="page-item {% if page_obj.number == p %}disabled{% endif %}">
                <a class="page-link" href="?{% url_replace page=p %}">{{ p }}</a>
            </li>
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">Last &raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    {% else %}
    <div class="alert alert-warning">No bulk notification created.</div>
    {% endif %}
</div>

{% endblock %}

fcm_notification/templates/notification/bulk_push/receivers.html
{% extends "notification/base.html" %}
{% load notification_extras %}
{% block 'main_content' %}
<div class="container">
    <h3 class="my-4">Bulk Notification Details</h3>
    <table class="table table-bordered table-sm mb-4">
        <tr>
            <th>Title</th>
            <td colspan="3">{{ bulk_request.title }}</td>
        </tr>
        <tr>
            <th>Message</th>
            <td colspan="3"><a href="{% url 'message_details' bulk_request.message.pk %}">{{ bulk_request.message.title }}</a></td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ bulk_request.get_status_display }}</td>
            <th>Created at</th>
            <td>{{ bulk_request.created_at }}</td>
        </tr>
    </table>
    {% if bulk_request.get_status_display == 'PROCESSING' %}
      <div class="alert alert-info" role="alert">
        Your uploaded file is still processing. Please refresh the page sometime later to view progress.
      </div>
    {% endif %}
    <h3 class="mb-2 mt-4">Notification receivers
      <span class="badge badge-secondary">{{ page_obj.paginator.count }}</span>
    </h3>
    <div class="row">
        <div class="col">
            <form class="form-inline my-3" action="">
                <label>Mobile</label>
                {{ search_form.mobile }}
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
        <div class="col text-right my-3">
          {% if bulk_request.get_status_display != 'PROCESSING' and page_obj %}
            <a href="{% url 'send_bulk_message' bulk_request.id %}"
               class="btn btn-primary px-4">Send</a>
          {% endif %}
          <a href="{% url 'bulk_message_send_request' bulk_request.id %}"
                 class="btn btn-info">Send Requests</a>
        </div>
    </div>

    {% if page_obj %}
    <table class="table mt-3">
        <thead>
            <tr>
                <th>Sl No</th>
                <th>Mobile</th>
                <th>Status</th>
                <th>Created at</th>
            </tr>
        </thead>
        <tbody>
            {% for msg_obj in  page_obj %}
            <tr>
                <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                <td>{{ msg_obj.mobile }}</td>
                <td>{{ msg_obj.get_status_display }}</td>
                <td>{{ msg_obj.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    {% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=1 %}">&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}

            {% for p in page_range %}
            <li class="page-item {% if page_obj.number == p %}disabled{% endif %}">
                <a class="page-link" href="?{% url_replace page=p %}">{{ p }}</a>
            </li>
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">Last &raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    {% else %}
      <div class="alert alert-info">No receiver added.</div>
    {% endif %}
</div>

{% endblock %}

fcm_notification/templates/notification/bulk_push/schedules.html
{% extends "notification/base.html" %}
{% load notification_extras %}
{% block 'main_content' %}
  <div class="container">
    {% include 'notification/common/notification_request.html' %}
    {% include 'notification/common/notification_request_menu_navs.html' with nav='SCHEDULE' %}

    {% if object_list %}
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Schedule ID</th>
            <th>Schedule Type</th>
            <th>Schedule Time</th>
            <th>Repeat Days</th>
            <th>Should Repeat</th>
            <th>Repeat Until</th>
            <th>Create Time</th>
            <th>Created By</th>
          </tr>
          </thead>
          <tbody>
          {% for obj in  object_list %}
            <tr>
              <td>{{ obj.id }}</td>
              <td>{{ obj.get_schedule_type_display }}</td>
              <td>{{ obj.schedule_time }}</td>
              <td>{{ obj.repeat_days }}</td>
              <td>{{ obj.should_repeat }}</td>
              <td>{{ obj.repeat_until }}</td>
              <td>{{ obj.created_at }}</td>
              <td>{{ obj.scheduled_by }}</td>
            </tr>
          {% endfor %}
          </tbody>
      </table>
      </div>
    {% else %}
      <div class="alert alert-info mt-3">This message is not scheduled yet.</div>
    {% endif %}
  </div>

{% endblock %}

fcm_notification/templates/notification/bulk_push/send_requests.html
{% extends "notification/base.html" %}
{% load notification_extras %}
{% block 'main_content' %}
  <div class="container">
    {% include 'notification/common/notification_request.html' %}
    {% include 'notification/common/notification_request_menu_navs.html' with nav='SEND_REQUEST' %}

    {% if object_list %}
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Status</th>
            <th>Total Receiver</th>
            <th>Active Receiver</th>
            <th>Chunk Size</th>
            <th>Total Chunk</th>
            <th>Total Success</th>
            <th>Total Failed</th>
            <th>Create Time</th>
            <th>Update Time</th>
            <th>Sent By</th>
          </tr>
          </thead>
          <tbody>
          {% for obj in  object_list %}
            <tr>
              {% if obj.get_status_display == 'SCHEDULED' %}
                <td>{{ obj.get_status_display }} ({{ obj.schedule_time }})</td>
              {% else %}
                <td>{{ obj.get_status_display }}</td>
              {% endif %}
              <td>{{ obj.receiver_count }}</td>
              <td>{{ obj.active_user_count }}</td>
              <td>{{ obj.chunk_size }}</td>
              <td>{{ obj.total_chunk }}</td>
              <td>{{ obj.total_success }}</td>
              <td>{{ obj.total_fail }}</td>
              <td>{{ obj.created_at }}</td>
              <td>{{ obj.updated_at }}</td>
              <td>{{ obj.created_by }}</td>
            </tr>
          {% endfor %}
          </tbody>
      </table>
      </div>
    {% else %}
      <div class="alert alert-info mt-3">This message is not sent yet.</div>
    {% endif %}
  </div>

{% endblock %}