fcm_notification/urls.py
from django.urls import path

from fcm_notification.api_views import (
    RegisterFcmTokenAPI, PushMessageAPI, SendPushMessageAPIView, PushMessageImageAPI
)
from fcm_notification.views import (
    create_push_message, PushMessageList, message_details, BulkMessageRequestList,
    create_bulk_message_request, SendBulkMessage, BulkMessageReceiversList, BulkMessageSendRequestView,
    BulkMessageSchedulesView, BulkMessageTagsView, edit_message, send_message, send_message_success
)

urlpatterns = [
    path('message/create', create_push_message, name='create_push_message'),
    path('message', PushMessageList.as_view(), name='push_message_list'),
    path('message/<int:message_id>', message_details, name='message_details'),
    path('message/bulk', BulkMessageRequestList.as_view(), name='bulk_message_list'),
    path('message/bulk/create', create_bulk_message_request, name='create_bulk_message'),
    path('message/bulk/<int:request_id>/send', SendBulkMessage.as_view(), name='send_bulk_message'),
    path('message/bulk/<int:request_id>/receivers', BulkMessageReceiversList.as_view(), name='bulk_message_receivers'),
    path('message/bulk/<int:request_id>/send-request', BulkMessageSendRequestView.as_view(),
         name='bulk_message_send_request'),
    path('message/bulk/<int:request_id>/schedules', BulkMessageSchedulesView.as_view(), name='bulk_message_schedules'),
    path('message/bulk/<int:request_id>/tags', BulkMessageTagsView.as_view(), name='bulk_message_tags'),
    path('message/<int:message_id>/edit', edit_message, name='edit_message'),
    path('message/<int:message_id>/send', send_message, name='send_message'),
    path('message/<int:message_id>/sent', send_message_success, name='message_sent'),
    path('fcm/register', RegisterFcmTokenAPI.as_view(), name='register_fcm_token'),
    path('message', PushMessageAPI.as_view(), name='add_push_message_api'),
    path('message/<int:id>', PushMessageAPI.as_view(), name='get_push_message_api'),
    path('message/<int:message_id>/send/<mobile:mobile_no>', SendPushMessageAPIView.as_view(),
         name='send_push_message_api'),
    path('message/image', PushMessageImageAPI.as_view(), name='push_message_image_api'),
]

fcm_notification/models.py
import uuid
from argparse import FileType

from django.core.validators import MinLengthValidator, MinValueValidator, URLValidator
from django.db import models
from django.forms.fields import URLField as FormURLField
from django_celery_beat.models import PeriodicTask

from fcm_notification.utilities.common_services import image_upload_path, notification_number_file_upload_path
from fcm_notification.utilities.validators import validate_file_size

MESSAGE_TYPES = (
    ('INFO', 'INFO'), 
    ('FILE_UPLOAD', 'FILE_UPLOAD'), 
    ('IMAGE_UPLOAD', 'IMAGE_UPLOAD'), 
    ('LINK', 'LINK'),
    ('POPUP_MESSAGE', 'POPUP_MESSAGE'),
)


class MessageCategory(models.TextChoices):
    GENERIC = 'GENERIC'
    CUSTOM = 'CUSTOM'


IMAGE_RESOLUTION_TYPES = (
    ('LOW', 'LOW'),
    ('MEDIUM', 'MEDIUM'),
    ('HIGH', 'HIGH'),
)

MSG_CONTENT_TYPE = (
    ('text', 'TEXT'),
    ('html', 'HTML'),
)

BULK_NOTIFICATION_STATUS = (
    (1, 'PROCESSING'),
    (2, 'READY'),
)

BULK_NOTIFICATION_SEND_STATUS = (
    (1, 'SCHEDULED'),
    (2, 'PROCESSING'),
    (3, 'COMPLETE'),
    (4, 'CANCELED'),
    (5, 'IN_PROGRESS'),
)


class ReceiverType(models.TextChoices):
    FILE = 'FILE'
    TG = 'TG'


class BulkScheduleType(models.TextChoices):
    ONE_TIME = 'ONE_TIME'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'


class AppInstallStatus(models.TextChoices):
    ACTIVE = 'ACTIVE'
    UNINSTALLED = 'UNINSTALLED'


class AiURLFormField(FormURLField):
    default_validators = [URLValidator(
        schemes=['http', 'https', 'ftp', 'ftps', 'external-http', 'external-https'])]


class AiURLField(models.CharField):
    default_validators = [URLValidator(
        schemes=['http', 'https', 'ftp', 'ftps', 'external-http', 'external-https'])]
    description = "URL"

    def __init__(self, verbose_name=None, name=None, **kwargs):
        kwargs.setdefault('max_length', 200)
        super().__init__(verbose_name, name, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        if kwargs.get("max_length") == 200:
            del kwargs['max_length']
        return name, path, args, kwargs

    def formfield(self, **kwargs):
        return super().formfield(**{
            'form_class': AiURLFormField,
            **kwargs,
        })


class FcmToken(models.Model):
    device_id = models.CharField(max_length=50, unique=True)
    token = models.CharField(max_length=255)
    app_version_number = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    app_status = models.CharField(
        max_length=15, null=False, blank=False, default=AppInstallStatus.ACTIVE.name,
        choices=AppInstallStatus.choices
    )

    class Meta:
        indexes = [
            models.Index(fields=['app_status'])
        ]

    def __str__(self):
        return self.device_id


class ImageRequest(models.Model):
    file_type = models.ForeignKey(FileType, on_delete=models.CASCADE)
    description = models.CharField(max_length=250, blank=True, null=True)
    resolution = models.CharField(choices=IMAGE_RESOLUTION_TYPES, max_length=8)
    is_live = models.BooleanField(default=False)

    class Meta:
        abstract = True


class ActionMessage(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return str(self.title)

    class Meta:
        abstract = True


class PushMessageImage(models.Model):
    thumbnail_img = models.ImageField(null=True, upload_to=image_upload_path, validators=[validate_file_size])
    full_img = models.ImageField(null=True, upload_to=image_upload_path, validators=[validate_file_size])


class PushMessage(models.Model):
    title = models.CharField(max_length=60)
    summary = models.CharField(max_length=250)
    body = models.CharField(max_length=5000)
    content_type = models.CharField(max_length=4, choices=MSG_CONTENT_TYPE, default='text')
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(choices=MESSAGE_TYPES, max_length=20)
    image = models.ForeignKey(PushMessageImage, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.CharField(choices=MessageCategory.choices, max_length=15)

    def __str__(self):
        return "{} - {}".format(self.id, self.title)


class FileRequestMessage(ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)


class FileTypeRequest(ImageRequest):
    title = models.CharField(max_length=100)
    file_request_message = models.ForeignKey(FileRequestMessage, on_delete=models.CASCADE, related_name='file_type_request_set')


class ImageRequestMessage(ImageRequest, ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    min_files = models.PositiveSmallIntegerField()
    max_files = models.PositiveSmallIntegerField()


class LinkMessage(ActionMessage):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    link_url = AiURLField()


class PopupMessage(models.Model):
    push_message = models.OneToOneField(PushMessage, on_delete=models.CASCADE)
    button_text = models.CharField(max_length=50, null=False, blank=False)
    display_type = models.CharField(max_length=25, null=False, blank=False, choices=(
        ('COMPLETE_MESSAGE', 'COMPLETE_MESSAGE'),
        ('IMAGE_MESSAGE', 'IMAGE_MESSAGE'),
    ))
    action_type = models.CharField(max_length=25, null=False, blank=False, choices=(
        ('OPEN_URL', 'OPEN_URL'),
        ('OPEN_ACTIVITY', 'OPEN_ACTIVITY'),
        ('DISMISS', 'DISMISS'),
    ))
    action_data = models.CharField(max_length=200, null=True, blank=True)
    start_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    min_delay = models.IntegerField(null=True, blank=True, default=0)


class MessageDeliveryLog(models.Model):
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=11, db_index=True)
    device_id = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=150)


class EventNotification(models.Model):
    event = models.PositiveSmallIntegerField(choices=EVENTS, unique=True)
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationRequest(models.Model):
    message = models.ForeignKey(PushMessage, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000, null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=BULK_NOTIFICATION_STATUS, default=1)
    receiver_count = models.IntegerField(null=False, default=0)
    created_by = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    receiver_type = models.CharField(max_length=15, null=False, blank=False, choices=ReceiverType.choices)

    class Meta:
        indexes = [
            models.Index(fields=['receiver_type'])
        ]

    def __str__(self):
        return str(self.title)


class BulkNotificationFile(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE)
    uploaded_file = models.FileField(
        null=False,
        max_length=150,
        upload_to=notification_number_file_upload_path
    )
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationReceiver(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE, related_name='receivers')
    mobile = models.CharField(max_length=11, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['mobile'], name='idx_bulk_notif_receiver_mobile')
        ]

    def __str__(self):
        return self.mobile


class BulkNotificationSendRequest(models.Model):
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=BULK_NOTIFICATION_SEND_STATUS, null=False, blank=False)
    receiver_count = models.IntegerField(null=False, blank=False)
    chunk_size = models.IntegerField(null=True, blank=True)
    total_chunk = models.IntegerField(null=True, blank=True)
    created_by = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    schedule_time = models.DateTimeField(null=True, blank=True)
    chunk_delay = models.IntegerField(null=False, blank=False, default=0)
    active_user_count = models.IntegerField(null=False, default=0)
    total_success = models.IntegerField(null=False, default=0)
    total_fail = models.IntegerField(null=False, default=0)
    message = models.ForeignKey(PushMessage, null=True, blank=True, on_delete=models.SET_NULL, related_name='+')


class BulkNotificationSendCount(models.Model):
    send_request = models.ForeignKey(BulkNotificationSendRequest, on_delete=models.CASCADE, related_name='send_counts')
    success_count = models.IntegerField(default=0, null=False, blank=False)
    failed_count = models.IntegerField(default=0, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)


class BulkNotificationSchedule(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    request = models.ForeignKey(BulkNotificationRequest, on_delete=models.CASCADE, related_name='schedules')
    task = models.ForeignKey(PeriodicTask, on_delete=models.CASCADE)
    schedule_type = models.CharField(max_length=15, null=False, blank=False, choices=BulkScheduleType.choices)
    schedule_time = models.TimeField(null=False, blank=False)
    should_repeat = models.BooleanField(null=False, blank=False, default=False)

fcm_notification/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from fcm_notification.models import MESSAGE_TYPES, FcmToken, PushMessage, BulkNotificationRequest
from fcm_notification.utilities.validators import MOBILE_REGEX

MESSAGE_TYPE_FILTERS = (('', '-- all --'),) + MESSAGE_TYPES


class SendPushMessageForm(forms.Form):
    mobile = forms.RegexField(regex=MOBILE_REGEX, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'minlength': 11, 'maxlength': 11}))

    def clean_mobile(self):
        mobile_no = self.cleaned_data['mobile']
        if mobile_no:
            device_ids = RegisteredUser.objects.filter(mobile=mobile_no, device_status='active').values_list('device_id')
            if len(device_ids) == 0:
                raise ValidationError("No active device found with this mobile")

            device_id_list = [x[0] for x in device_ids]
            fcm_toke_count = FcmToken.objects.filter(device_id__in=device_id_list).count()
            if fcm_toke_count == 0:
                raise ValidationError("No active device of this mobile is registered to Firebase")
        
        return mobile_no


class SearchMessageForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control mx-2'}))
    type = forms.ChoiceField(required=False, choices=MESSAGE_TYPE_FILTERS, widget=forms.Select(attrs={'class': 'form-control mx-2'}))


class SearchBulkMessageForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control mx-2'}))


class SearchBulkMessageReceiverForm(forms.Form):
    mobile = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control mx-2', 'minlength': '11', 'maxlength': '11'}))


class EditMessageForm(forms.ModelForm):
    class Meta:
        model = PushMessage
        fields = ('title', 'summary', 'body', )


class GetPromoForm(forms.Form):
    app_version = forms.IntegerField(min_value=1, max_value=2147483647, required=True)


class CreateBulkMessageForm(forms.ModelForm):
    receiver_list = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control-file', 'accept': ".csv"}),
        validators=[FileExtensionValidator(allowed_extensions=['csv'], message='Only csv file is allowed')]
    )

    class Meta:
        model = BulkNotificationRequest
        exclude = ('created_by', 'status', 'receiver_count')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
        }


class CreateTgNotificationForm(forms.ModelForm):
    class Meta:
        model = BulkNotificationRequest
        exclude = ('created_by', 'status', 'receiver_count')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
            'receiving_tags': forms.SelectMultiple(attrs={'class': 'form-control', 'required': True}),
        }

fcm_notification/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tallykhata Admin Panel</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <script src="https://unpkg.com/jquery@3.6.0/dist/jquery.min.js" type="text/javascript"></script>
    <script src="https://unpkg.com/bootstrap@4.6.0/dist/js/bootstrap.min.js" type="text/javascript"></script>
    {% block 'extra_head' %}{% endblock %}
</head>

<body>
    {% block 'content' %}{% endblock %}
    {% block 'extra_footer' %}{% endblock %}
</body>

</html>

fcm_notification/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block 'content' %}
<div class="container">
        <h1>Tallykhata Admin Panel</h1>
        <p class="lead">Portal for Tallykhata administration.</p>

        <h2 class="my-4">Start from here</h2>
        
        <div class="row">
            {% if user.is_authenticated %} 
            {% if perms.notification.add_pushmessage %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'images/message.png' %}" class="card-img-top" alt="Messages">
                    <div class="card-body">
                        <h5 class="card-title">Messages</h5>
                        <p class="card-text">Create and send push messages to app users. See list of previous messages and resend them.</p>
                        <a href="{% url 'push_message_list' %}" class="btn btn-primary">Go</a>
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'images/analysis.jpg' %}" class="card-img-top" alt="Data">
                    <div class="card-body">
                        <h5 class="card-title">View data</h5>
                        <p class="card-text">View app users data and other reports from here. Manage the authentication, authorization and other properties.</p>
                        <a href="/admin" class="btn btn-primary">Go</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'images/browse.jpg' %}" class="card-img-top" alt="Website">
                    <div class="card-body">
                        <h5 class="card-title">Website</h5>
                        <p class="card-text">Looking for the Tallykhata website instead? Go to website. The playstore link is also provided in the website.</p>
                        <a href="https://www.tallykhata.com/" class="btn btn-primary" target="_blank">Go</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'images/support.jpg' %}" class="card-img-top" alt="Support">
                    <div class="card-body">
                        <h5 class="card-title">Customer care</h5>
                        <p class="card-text">Investigate common customer issues and perform specific actions.</p>
                        <a href="{% url 'support_home' %}" class="btn btn-primary">Go</a>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'images/lock.jpg' %}" class="card-img-top" alt="Login">
                    <div class="card-body">
                        <h5 class="card-title">Login</h5>
                        <p class="card-text">You are not logged in yet. Please login first to get access to the portal.</p>
                        <a href="/admin/login?next=/" class="btn btn-primary">Go</a>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}